// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: athlete.sql

package query

import (
	"context"

	"github.com/google/uuid"
)

const getAthlete = `-- name: GetAthlete :one
SELECT id, handle, display_name, created_at
FROM athlete
WHERE id = $1
`

func (q *Queries) GetAthlete(ctx context.Context, id uuid.UUID) (Athlete, error) {
	row := q.db.QueryRow(ctx, getAthlete, id)
	var i Athlete
	err := row.Scan(
		&i.ID,
		&i.Handle,
		&i.DisplayName,
		&i.CreatedAt,
	)
	return i, err
}
