// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: club.sql

package query

import (
	"context"

	"github.com/google/uuid"
)

const incrementAppearanceCounter = `-- name: IncrementAppearanceCounter :one
INSERT INTO appearance_counter (athlete_id, metric, value)
VALUES ($1, $2, 1)
ON CONFLICT (athlete_id, metric) DO UPDATE SET value = appearance_counter.value + 1
RETURNING value
`

type IncrementAppearanceCounterParams struct {
	AthleteID uuid.UUID `json:"athlete_id"`
	Metric    string    `json:"metric"`
}

// Single atomic statement: Postgres serializes concurrent callers, so two rapid clicks for the
// same athlete always get distinct, correctly-ordered values (fixes a real race — see migration
// 0004 for the incident this replaced: reading milestone.progress then adding 1 in Go).
func (q *Queries) IncrementAppearanceCounter(ctx context.Context, arg IncrementAppearanceCounterParams) (int64, error) {
	row := q.db.QueryRow(ctx, incrementAppearanceCounter, arg.AthleteID, arg.Metric)
	var value int64
	err := row.Scan(&value)
	return value, err
}

const listRoster = `-- name: ListRoster :many
SELECT a.id AS athlete_id, a.display_name,
       m.id AS milestone_id, m.metric, m.progress, m.target, m.tranche, m.state, m.amount, m.currency
FROM athlete a
JOIN milestone m ON m.athlete_id = a.id
ORDER BY a.display_name
`

type ListRosterRow struct {
	AthleteID   uuid.UUID `json:"athlete_id"`
	DisplayName string    `json:"display_name"`
	MilestoneID uuid.UUID `json:"milestone_id"`
	Metric      string    `json:"metric"`
	Progress    int64     `json:"progress"`
	Target      int64     `json:"target"`
	Tranche     int64     `json:"tranche"`
	State       string    `json:"state"`
	Amount      int64     `json:"amount"`
	Currency    string    `json:"currency"`
}

// Club-side view across every player under contract — unlike the /me/* queries this is
// intentionally not scoped to one athlete_id.
func (q *Queries) ListRoster(ctx context.Context) ([]ListRosterRow, error) {
	rows, err := q.db.Query(ctx, listRoster)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRosterRow{}
	for rows.Next() {
		var i ListRosterRow
		if err := rows.Scan(
			&i.AthleteID,
			&i.DisplayName,
			&i.MilestoneID,
			&i.Metric,
			&i.Progress,
			&i.Target,
			&i.Tranche,
			&i.State,
			&i.Amount,
			&i.Currency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
