// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: contract_document.sql

package query

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const insertContractDocument = `-- name: InsertContractDocument :exec
INSERT INTO contract_document (id, athlete_id, contract_id, filename, content_type, raw_text, file_data, label, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertContractDocumentParams struct {
	ID          uuid.UUID   `json:"id"`
	AthleteID   uuid.UUID   `json:"athlete_id"`
	ContractID  pgtype.UUID `json:"contract_id"`
	Filename    string      `json:"filename"`
	ContentType string      `json:"content_type"`
	RawText     string      `json:"raw_text"`
	FileData    []byte      `json:"file_data"`
	Label       string      `json:"label"`
	Status      string      `json:"status"`
}

func (q *Queries) InsertContractDocument(ctx context.Context, arg InsertContractDocumentParams) error {
	_, err := q.db.Exec(ctx, insertContractDocument,
		arg.ID,
		arg.AthleteID,
		arg.ContractID,
		arg.Filename,
		arg.ContentType,
		arg.RawText,
		arg.FileData,
		arg.Label,
		arg.Status,
	)
	return err
}

const listContractDocumentsByAthlete = `-- name: ListContractDocumentsByAthlete :many
SELECT id, athlete_id, contract_id, filename, content_type, raw_text, label, status, created_at
FROM contract_document
WHERE athlete_id = $1
ORDER BY created_at DESC
`

type ContractDocumentRow struct {
	ID          uuid.UUID   `json:"id"`
	AthleteID   uuid.UUID   `json:"athlete_id"`
	ContractID  pgtype.UUID `json:"contract_id"`
	Filename    string      `json:"filename"`
	ContentType string      `json:"content_type"`
	RawText     string      `json:"raw_text"`
	Label       string      `json:"label"`
	Status      string      `json:"status"`
	CreatedAt   time.Time   `json:"created_at"`
}

func (q *Queries) ListContractDocumentsByAthlete(ctx context.Context, athleteID uuid.UUID) ([]ContractDocumentRow, error) {
	rows, err := q.db.Query(ctx, listContractDocumentsByAthlete, athleteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ContractDocumentRow{}
	for rows.Next() {
		var i ContractDocumentRow
		if err := rows.Scan(
			&i.ID,
			&i.AthleteID,
			&i.ContractID,
			&i.Filename,
			&i.ContentType,
			&i.RawText,
			&i.Label,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getContractDocument = `-- name: GetContractDocument :one
SELECT id, athlete_id, contract_id, filename, content_type, raw_text, label, status, created_at
FROM contract_document
WHERE id = $1 AND athlete_id = $2
`

type GetContractDocumentParams struct {
	ID        uuid.UUID `json:"id"`
	AthleteID uuid.UUID `json:"athlete_id"`
}

func (q *Queries) GetContractDocument(ctx context.Context, arg GetContractDocumentParams) (ContractDocumentRow, error) {
	row := q.db.QueryRow(ctx, getContractDocument, arg.ID, arg.AthleteID)
	var i ContractDocumentRow
	err := row.Scan(
		&i.ID,
		&i.AthleteID,
		&i.ContractID,
		&i.Filename,
		&i.ContentType,
		&i.RawText,
		&i.Label,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const updateContractDocumentText = `-- name: UpdateContractDocumentText :exec
UPDATE contract_document
SET raw_text = $3, status = 'analyzed'
WHERE id = $1 AND athlete_id = $2
`

type UpdateContractDocumentTextParams struct {
	ID        uuid.UUID `json:"id"`
	AthleteID uuid.UUID `json:"athlete_id"`
	RawText   string    `json:"raw_text"`
}

func (q *Queries) UpdateContractDocumentText(ctx context.Context, arg UpdateContractDocumentTextParams) error {
	_, err := q.db.Exec(ctx, updateContractDocumentText, arg.ID, arg.AthleteID, arg.RawText)
	return err
}

const deleteContractDocument = `-- name: DeleteContractDocument :exec
DELETE FROM contract_document
WHERE id = $1 AND athlete_id = $2
`

type DeleteContractDocumentParams struct {
	ID        uuid.UUID `json:"id"`
	AthleteID uuid.UUID `json:"athlete_id"`
}

func (q *Queries) DeleteContractDocument(ctx context.Context, arg DeleteContractDocumentParams) error {
	_, err := q.db.Exec(ctx, deleteContractDocument, arg.ID, arg.AthleteID)
	return err
}
