// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: contract.sql

package query

import (
	"context"

	"github.com/google/uuid"
)

const listClausesForAthleteContract = `-- name: ListClausesForAthleteContract :many
SELECT c.id, c.contract_id, c.kind, c.params, c.created_at
FROM clause c
JOIN contract ct ON ct.id = c.contract_id
WHERE c.contract_id = $1
  AND ct.athlete_id = $2
ORDER BY c.created_at
`

type ListClausesForAthleteContractParams struct {
	ContractID uuid.UUID `json:"contract_id"`
	AthleteID  uuid.UUID `json:"athlete_id"`
}

func (q *Queries) ListClausesForAthleteContract(ctx context.Context, arg ListClausesForAthleteContractParams) ([]Clause, error) {
	rows, err := q.db.Query(ctx, listClausesForAthleteContract, arg.ContractID, arg.AthleteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Clause{}
	for rows.Next() {
		var i Clause
		if err := rows.Scan(
			&i.ID,
			&i.ContractID,
			&i.Kind,
			&i.Params,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContractsByAthlete = `-- name: ListContractsByAthlete :many
SELECT id, athlete_id, club_from, club_to, currency, fixed_amount, salary, status, created_at
FROM contract
WHERE athlete_id = $1
ORDER BY created_at
`

func (q *Queries) ListContractsByAthlete(ctx context.Context, athleteID uuid.UUID) ([]Contract, error) {
	rows, err := q.db.Query(ctx, listContractsByAthlete, athleteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Contract{}
	for rows.Next() {
		var i Contract
		if err := rows.Scan(
			&i.ID,
			&i.AthleteID,
			&i.ClubFrom,
			&i.ClubTo,
			&i.Currency,
			&i.FixedAmount,
			&i.Salary,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
