// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package query

import (
	"context"
	"time"
)

const listRecentMilestoneEvents = `-- name: ListRecentMilestoneEvents :many
SELECT event_type, payload, created_at
FROM outbox
WHERE subject = 'events.milestone'
ORDER BY created_at DESC
LIMIT $1
`

type ListRecentMilestoneEventsRow struct {
	EventType string    `json:"event_type"`
	Payload   []byte    `json:"payload"`
	CreatedAt time.Time `json:"created_at"`
}

// Unscoped: backs the ClubBoard feed, which shows every player's events.
func (q *Queries) ListRecentMilestoneEvents(ctx context.Context, limit int32) ([]ListRecentMilestoneEventsRow, error) {
	rows, err := q.db.Query(ctx, listRecentMilestoneEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecentMilestoneEventsRow{}
	for rows.Next() {
		var i ListRecentMilestoneEventsRow
		if err := rows.Scan(&i.EventType, &i.Payload, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentMilestoneEventsForAthlete = `-- name: ListRecentMilestoneEventsForAthlete :many

SELECT event_type, payload, created_at
FROM outbox
WHERE subject = 'events.milestone' AND payload->>'athlete_id' = $1::text
ORDER BY created_at DESC
LIMIT $2
`

type ListRecentMilestoneEventsForAthleteParams struct {
	Column1 string `json:"column_1"`
	Limit   int32  `json:"limit"`
}

type ListRecentMilestoneEventsForAthleteRow struct {
	EventType string    `json:"event_type"`
	Payload   []byte    `json:"payload"`
	CreatedAt time.Time `json:"created_at"`
}

// The transactional outbox already IS a durable, ordered event log (every MilestoneAdvanced /
// MilestoneFulfilled ever emitted, with its payload and timestamp). Re-reading it on page load
// is how both dashboards' live-feed panels survive a browser refresh instead of coming back
// empty — the WebSocket only ever delivers events that happen *after* it connects.
func (q *Queries) ListRecentMilestoneEventsForAthlete(ctx context.Context, arg ListRecentMilestoneEventsForAthleteParams) ([]ListRecentMilestoneEventsForAthleteRow, error) {
	rows, err := q.db.Query(ctx, listRecentMilestoneEventsForAthlete, arg.Column1, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecentMilestoneEventsForAthleteRow{}
	for rows.Next() {
		var i ListRecentMilestoneEventsForAthleteRow
		if err := rows.Scan(&i.EventType, &i.Payload, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
