// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ingest.sql

package query

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const insertAudit = `-- name: InsertAudit :exec
INSERT INTO audit_log (athlete_id, action, detail)
VALUES ($1, $2, $3)
`

type InsertAuditParams struct {
	AthleteID pgtype.UUID `json:"athlete_id"`
	Action    string      `json:"action"`
	Detail    string      `json:"detail"`
}

func (q *Queries) InsertAudit(ctx context.Context, arg InsertAuditParams) error {
	_, err := q.db.Exec(ctx, insertAudit, arg.AthleteID, arg.Action, arg.Detail)
	return err
}

const insertInboundEvent = `-- name: InsertInboundEvent :one
INSERT INTO inbound_event (source_event_id, kind, raw)
VALUES ($1, $2, $3)
ON CONFLICT (source_event_id) DO NOTHING
RETURNING source_event_id
`

type InsertInboundEventParams struct {
	SourceEventID string `json:"source_event_id"`
	Kind          string `json:"kind"`
	Raw           []byte `json:"raw"`
}

// Returns the row only on first insert; ON CONFLICT DO NOTHING => no row (pgx.ErrNoRows) on duplicate.
func (q *Queries) InsertInboundEvent(ctx context.Context, arg InsertInboundEventParams) (string, error) {
	row := q.db.QueryRow(ctx, insertInboundEvent, arg.SourceEventID, arg.Kind, arg.Raw)
	var source_event_id string
	err := row.Scan(&source_event_id)
	return source_event_id, err
}

const insertOutbox = `-- name: InsertOutbox :one
INSERT INTO outbox (aggregate, event_type, subject, payload)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type InsertOutboxParams struct {
	Aggregate string `json:"aggregate"`
	EventType string `json:"event_type"`
	Subject   string `json:"subject"`
	Payload   []byte `json:"payload"`
}

func (q *Queries) InsertOutbox(ctx context.Context, arg InsertOutboxParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertOutbox,
		arg.Aggregate,
		arg.EventType,
		arg.Subject,
		arg.Payload,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertPayoutEvent = `-- name: InsertPayoutEvent :exec
INSERT INTO payout_event (id, athlete_id, milestone_id, boundary, amount, currency, status)
VALUES ($1, $2, $3, $4, $5, $6, 'expected')
ON CONFLICT (milestone_id, boundary) DO NOTHING
`

type InsertPayoutEventParams struct {
	ID          uuid.UUID `json:"id"`
	AthleteID   uuid.UUID `json:"athlete_id"`
	MilestoneID uuid.UUID `json:"milestone_id"`
	Boundary    int64     `json:"boundary"`
	Amount      int64     `json:"amount"`
	Currency    string    `json:"currency"`
}

func (q *Queries) InsertPayoutEvent(ctx context.Context, arg InsertPayoutEventParams) error {
	_, err := q.db.Exec(ctx, insertPayoutEvent,
		arg.ID,
		arg.AthleteID,
		arg.MilestoneID,
		arg.Boundary,
		arg.Amount,
		arg.Currency,
	)
	return err
}

const insertPerformanceStat = `-- name: InsertPerformanceStat :exec
INSERT INTO performance_stat (id, athlete_id, metric, value, source_event_id)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (source_event_id) DO NOTHING
`

type InsertPerformanceStatParams struct {
	ID            uuid.UUID `json:"id"`
	AthleteID     uuid.UUID `json:"athlete_id"`
	Metric        string    `json:"metric"`
	Value         int64     `json:"value"`
	SourceEventID string    `json:"source_event_id"`
}

func (q *Queries) InsertPerformanceStat(ctx context.Context, arg InsertPerformanceStatParams) error {
	_, err := q.db.Exec(ctx, insertPerformanceStat,
		arg.ID,
		arg.AthleteID,
		arg.Metric,
		arg.Value,
		arg.SourceEventID,
	)
	return err
}

const listUnpublishedOutbox = `-- name: ListUnpublishedOutbox :many
SELECT id, subject, payload
FROM outbox
WHERE published_at IS NULL
ORDER BY id
LIMIT $1
`

type ListUnpublishedOutboxRow struct {
	ID      int64  `json:"id"`
	Subject string `json:"subject"`
	Payload []byte `json:"payload"`
}

func (q *Queries) ListUnpublishedOutbox(ctx context.Context, limit int32) ([]ListUnpublishedOutboxRow, error) {
	rows, err := q.db.Query(ctx, listUnpublishedOutbox, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUnpublishedOutboxRow{}
	for rows.Next() {
		var i ListUnpublishedOutboxRow
		if err := rows.Scan(&i.ID, &i.Subject, &i.Payload); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOutboxPublished = `-- name: MarkOutboxPublished :exec
UPDATE outbox SET published_at = now() WHERE id = $1
`

func (q *Queries) MarkOutboxPublished(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markOutboxPublished, id)
	return err
}
