// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: milestone.sql

package query

import (
	"context"

	"github.com/google/uuid"
)

const listMilestonesByAthlete = `-- name: ListMilestonesByAthlete :many
SELECT id, athlete_id, clause_id, metric, target, tranche, max_repeats, amount, currency, progress, state, updated_at
FROM milestone
WHERE athlete_id = $1
ORDER BY updated_at DESC
`

func (q *Queries) ListMilestonesByAthlete(ctx context.Context, athleteID uuid.UUID) ([]Milestone, error) {
	rows, err := q.db.Query(ctx, listMilestonesByAthlete, athleteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Milestone{}
	for rows.Next() {
		var i Milestone
		if err := rows.Scan(
			&i.ID,
			&i.AthleteID,
			&i.ClauseID,
			&i.Metric,
			&i.Target,
			&i.Tranche,
			&i.MaxRepeats,
			&i.Amount,
			&i.Currency,
			&i.Progress,
			&i.State,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMilestonesByAthleteMetric = `-- name: ListMilestonesByAthleteMetric :many
SELECT id, athlete_id, clause_id, metric, target, tranche, max_repeats, amount, currency, progress, state, updated_at
FROM milestone
WHERE athlete_id = $1 AND metric = $2
FOR UPDATE
`

type ListMilestonesByAthleteMetricParams struct {
	AthleteID uuid.UUID `json:"athlete_id"`
	Metric    string    `json:"metric"`
}

func (q *Queries) ListMilestonesByAthleteMetric(ctx context.Context, arg ListMilestonesByAthleteMetricParams) ([]Milestone, error) {
	rows, err := q.db.Query(ctx, listMilestonesByAthleteMetric, arg.AthleteID, arg.Metric)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Milestone{}
	for rows.Next() {
		var i Milestone
		if err := rows.Scan(
			&i.ID,
			&i.AthleteID,
			&i.ClauseID,
			&i.Metric,
			&i.Target,
			&i.Tranche,
			&i.MaxRepeats,
			&i.Amount,
			&i.Currency,
			&i.Progress,
			&i.State,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMilestoneProgress = `-- name: UpdateMilestoneProgress :exec
UPDATE milestone
SET progress = $2, state = $3, updated_at = now()
WHERE id = $1
`

type UpdateMilestoneProgressParams struct {
	ID       uuid.UUID `json:"id"`
	Progress int64     `json:"progress"`
	State    string    `json:"state"`
}

func (q *Queries) UpdateMilestoneProgress(ctx context.Context, arg UpdateMilestoneProgressParams) error {
	_, err := q.db.Exec(ctx, updateMilestoneProgress, arg.ID, arg.Progress, arg.State)
	return err
}
