// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package query

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AppearanceCounter struct {
	AthleteID uuid.UUID `json:"athlete_id"`
	Metric    string    `json:"metric"`
	Value     int64     `json:"value"`
}

type Athlete struct {
	ID          uuid.UUID `json:"id"`
	Handle      string    `json:"handle"`
	DisplayName string    `json:"display_name"`
	CreatedAt   time.Time `json:"created_at"`
}

type AuditLog struct {
	ID        int64       `json:"id"`
	AthleteID pgtype.UUID `json:"athlete_id"`
	Action    string      `json:"action"`
	Detail    string      `json:"detail"`
	At        time.Time   `json:"at"`
}

type Clause struct {
	ID         uuid.UUID `json:"id"`
	ContractID uuid.UUID `json:"contract_id"`
	Kind       string    `json:"kind"`
	Params     []byte    `json:"params"`
	CreatedAt  time.Time `json:"created_at"`
}

type Contract struct {
	ID          uuid.UUID `json:"id"`
	AthleteID   uuid.UUID `json:"athlete_id"`
	ClubFrom    string    `json:"club_from"`
	ClubTo      string    `json:"club_to"`
	Currency    string    `json:"currency"`
	FixedAmount int64     `json:"fixed_amount"`
	Salary      int64     `json:"salary"`
	Status      string    `json:"status"`
	CreatedAt   time.Time `json:"created_at"`
}

type InboundEvent struct {
	SourceEventID string    `json:"source_event_id"`
	Kind          string    `json:"kind"`
	Raw           []byte    `json:"raw"`
	ReceivedAt    time.Time `json:"received_at"`
}

type Milestone struct {
	ID         uuid.UUID `json:"id"`
	AthleteID  uuid.UUID `json:"athlete_id"`
	ClauseID   uuid.UUID `json:"clause_id"`
	Metric     string    `json:"metric"`
	Target     int64     `json:"target"`
	Tranche    int64     `json:"tranche"`
	MaxRepeats int64     `json:"max_repeats"`
	Amount     int64     `json:"amount"`
	Currency   string    `json:"currency"`
	Progress   int64     `json:"progress"`
	State      string    `json:"state"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type Outbox struct {
	ID          int64              `json:"id"`
	Aggregate   string             `json:"aggregate"`
	EventType   string             `json:"event_type"`
	Subject     string             `json:"subject"`
	Payload     []byte             `json:"payload"`
	CreatedAt   time.Time          `json:"created_at"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
}

type PayoutEvent struct {
	ID          uuid.UUID `json:"id"`
	AthleteID   uuid.UUID `json:"athlete_id"`
	MilestoneID uuid.UUID `json:"milestone_id"`
	Boundary    int64     `json:"boundary"`
	Amount      int64     `json:"amount"`
	Currency    string    `json:"currency"`
	Status      string    `json:"status"`
	CreatedAt   time.Time `json:"created_at"`
}

type PerformanceStat struct {
	ID            uuid.UUID `json:"id"`
	AthleteID     uuid.UUID `json:"athlete_id"`
	Metric        string    `json:"metric"`
	Value         int64     `json:"value"`
	SourceEventID string    `json:"source_event_id"`
	ObservedAt    time.Time `json:"observed_at"`
}
